version: '3.3'

services:

  db:
    container_name: al_db
    build:
      context: './db'
      dockerfile: Dockerfile
    ports:
      - 5436:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  server:
    container_name: al_server
    build:
      context: './server'
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app:cached
    ports:
      - 5000:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/active_learner
    depends_on:
      - db
      - elasticsearch
    links:
      - db
      - elasticsearch

  client:
    container_name: al_client
    build:
      context: './client'
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app:cached
      # - './client/node_modules:/usr/src/app/node_modules'
      # - '/usr/src/app/node_modules'
    ports:
      - '3006:3000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    links:
      - server

  elasticsearch:
    container_name: al_elasticsearch
    build:
      context: './elasticsearch'
    volumes:
      - ./elasticsearch/esdata:/usr/share/elasticsearch/data:cached
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:cached
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - 9200:9200
